language: node_js

node_js:
  - '6'
  - '7'

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn run lerna -- bootstrap
  - yarn run lerna -- run build

script:
  - yarn run lint
  - yarn test
